version: '2'

services:
  redis:
    image: bitnami/redis:6.0
    container_name: cache
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '6379:6379'
  # otherservices:
  #   build: .
  #   environment:
  #     - PORT=8080
  #     - NODE_ENV=production
  #     - MONGO_URI=${MONGO_URI}
  #     - REDIS_URL=${REDIS_URL}
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #   ports:
  #     - '8080:8080'
